
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled
- name: restart elastic-agent
  become: yes
  service: name=elastic-agent state=restarted enabled=yes
  register: elastic_agent_restarted
