# ----------------------------------------------------------------------------
# Start elasticagent
# ----------------------------------------------------------------------------
---

- name: Start elasticagent process
  shell: 'nohup {{ elasticagent_exe }} --setup >/dev/null 2>&1 &'
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  async: 5
  poll: 0
  register: start_elasticagent_process